CXX = g++
CXXFLAGS = -O2 -Wall -std=c++17
THREAD = ${CXXFLAGS} -pthread

target=pgsnp ndrop merge grttbv splQTL allele2g amat combine obvped simPed

all:    ${target}

.phony: clean

clean:
	rm -f ${target}
